// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	orders "wb_internship/pkg/orders"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// LoadCache mocks base method.
func (m *MockRepo) LoadCache() (map[int]*orders.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCache")
	ret0, _ := ret[0].(map[int]*orders.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCache indicates an expected call of LoadCache.
func (mr *MockRepoMockRecorder) LoadCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCache", reflect.TypeOf((*MockRepo)(nil).LoadCache))
}

// Save mocks base method.
func (m *MockRepo) Save(order orders.Order) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", order)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepoMockRecorder) Save(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepo)(nil).Save), order)
}
